export const products = [
  {
    id: 1,
    name: "Sate Ayam",
    image: require("../assets/foods/sate ayam.jpg"),
    category: "makanan",
    price: 22000,
  },
  {
    id: 2,
    name: "Sate Kambing",
    image: require("../assets/foods/sate kambing.jpg"),
    category: "makanan",
    price: 30000,
  },
  {
    id: 3,
    name: "Ayam Goreng Dada",
    image: require("../assets/foods/ayam goreng paha.jpg"),
    category: "makanan",
    price: 20000,
  },
  {
    id: 4,
    name: "Soto Ayam",
    image: require("../assets/foods/soto ayam.jpg"),
    category: "makanan",
    price: 13000,
  },
  {
    id: 5,
    name: "Sop Kambing",
    image: require("../assets/foods/sop kambing.jpg"),
    category: "makanan",
    price: 22000,
  },
  {
    id: 6,
    name: "Lele Goreng",
    image: require("../assets/foods/lele goreng.jpg"),
    category: "makanan",
    price: 13000,
  },
  {
    id: 7,
    name: "Ayam Goreng Paha",
    image: require("../assets/foods/ayam goreng paha.jpg"),
    category: "makanan",
    price: 20000,
  },
  {
    id: 8,
    name: "Bebek Rica-rica",
    image: require("../assets/foods/bebek rica rica.jpg"),
    category: "makanan",
    price: 25000,
  },
  {
    id: 9,
    name: "Ayam Bakar",
    image: require("../assets/foods/ayam bakar.jpg"),
    category: "makanan",
    price: 20000,
  },
  {
    id: 10,
    name: "Nasi Goreng",
    image: require("../assets/foods/nasi goreng.jpg"),
    category: "makanan",
    price: 15000,
  },
  {
    id: 12,
    name: "Es Teh Manis",
    image: require("../assets/foods/es teh manis.jpg"),
    category: "minuman",
    price: 4000,
  },
  {
    id: 13,
    name: "Es stroberry",
    image: require("../assets/foods/es stroberry.jpg"),
    category: "minuman",
    price: 5000,
  },
  {
    id: 14,
    name: "Es Jeruk",
    image: require("../assets/foods/es jeruk.jpg"),
    category: "minuman",
    price: 5000,
  },
];

// import makanan from "../assets/foods/makanan1.jpg"
