export const products = [
  {
    id: 1,
    name: "makanan1",
    image: require("../assets/foods/makanan1.png"),
    category: "makanan",
    price: 13000,
  },
  {
    id: 2,
    name: "makanan2",
    image: require("../assets/foods/makanan2.png"),
    category: "makanan",
    price: 15000,
  },
  {
    id: 3,
    name: "makanan3",
    image: require("../assets/foods/makanan3.jpg"),
    category: "makanan",
    price: 20000,
  },
  {
    id: 4,
    name: "makanan4",
    image: require("../assets/foods/makanan4.jpg"),
    category: "makanan",
    price: 25000,
  },
  {
    id: 5,
    name: "makanan5",
    image: require("../assets/foods/makanan1.png"),
    category: "makanan",
    price: 13000,
  },
  {
    id: 6,
    name: "makanan6",
    image: require("../assets/foods/makanan2.png"),
    category: "makanan",
    price: 15000,
  },
  {
    id: 7,
    name: "makanan7",
    image: require("../assets/foods/makanan3.jpg"),
    category: "makanan",
    price: 20000,
  },
  {
    id: 8,
    name: "makanan8",
    image: require("../assets/foods/makanan4.jpg"),
    category: "makanan",
    price: 25000,
  },
  {
    id: 9,
    name: "makanan9",
    image: require("../assets/foods/makanan3.jpg"),
    category: "makanan",
    price: 20000,
  },
  {
    id: 10,
    name: "makanan10",
    image: require("../assets/foods/makanan4.jpg"),
    category: "makanan",
    price: 25000,
  },
  {
    id: 11,
    name: "makanan11",
    image: require("../assets/foods/makanan4.jpg"),
    category: "makanan",
    price: 25000,
  },
];

// import makanan from "../assets/foods/makanan1.jpg"
